name: Build Multiple Platforms

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macOS
            os: macos-latest
          - platform: Windows
            os: windows-latest
          - platform: Linux
            os: ubuntu-latest
          - platform: Android
            os: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build ${{ matrix.platform }}
        uses: aghastmuffin/beeware-builder@v0.1.2
        with:
          platform: ${{ matrix.platform }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-app
          path: dist/*
