uses: aghastmuffin/beeware-build@0.1.2
  with:
    # Target platform to build (macOS, Windows, Linux, or Android)
    platform: 
    # Python version to use for building
    python-version: # optional, default is 3.11
    # Briefcase version to install
    briefcase-version: # optional, default is latest
    # Directory to output built packages
    output-path: # optional, default is dist
